# Generated by Django 6.0.4 on 2026-05-12 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0004_alter_clubesregistrados_coordinador_deportivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temporada', models.CharField()),
                ('nombre', models.CharField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('partidos_ganados', models.IntegerField(default=0)),
                ('partidos_empatados', models.IntegerField(default=0)),
                ('partidos_perdidos', models.IntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.categoria')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.clubesregistrados')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.torneo')),
            ],
            options={
                'unique_together': {('torneo', 'club')},
            },
        ),
    ]
