# Generated by Django 6.0.4 on 2026-05-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
