# Generated by Django 6.0.4 on 2026-05-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_torneo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='torneo_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
