# Generated by Django 6.0.4 on 2026-05-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_torneo_torneo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='activo',
        ),
        migrations.AddField(
            model_name='torneo',
            name='estado',
            field=models.CharField(default='Inactivo'),
        ),
    ]
