# Generated by Django 6.0.4 on 2026-05-05 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClubesRegistrados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_siglas', models.CharField(unique=True)),
                ('nombre_completo', models.CharField()),
                ('nombre_corto', models.CharField(max_length=30, null=True)),
                ('localidad', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_cambio', models.DateField(null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.categoria')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.clubesregistrados')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.rol')),
            ],
        ),
    ]
