# Generated by Django 6.0.4 on 2026-04-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubesRegistrados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField()),
                ('nombre_corto', models.CharField(max_length=30, null=True)),
                ('localidad', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
