# Generated by Django 6.0.4 on 2026-04-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubesregistrados',
            name='nombre_siglas',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
