# Generated by Django 6.0.4 on 2026-04-20 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_clubesregistrados_nombre_siglas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_cambio', models.DateField(null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.categoria')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.clubesregistrados')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.rol')),
            ],
        ),
    ]
