# Generated by Django 6.0.4 on 2026-05-10 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_alter_clubesregistrados_coordinador_deportivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubesregistrados',
            name='coordinador_deportivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club', to=settings.AUTH_USER_MODEL),
        ),
    ]
