# Generated by Django 6.0.4 on 2026-04-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_categoria_persona_rol_personarol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clubesregistrados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_persona',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
