# Generated by Django 6.0.4 on 2026-05-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0004_alter_categoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubesregistrados',
            name='nombre_siglas',
            field=models.CharField(unique=True),
        ),
    ]
