# Generated by Django 6.0.4 on 2026-05-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_direccion'),
        ('clubes', '0002_clubesregistrados_coordinador_deportivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='club',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinadores', to='clubes.clubesregistrados'),
        ),
    ]
