# Generated by Django 6.0.4 on 2026-05-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='club',
        ),
    ]
